### ISSUE TITLE
Test option to replace the primary key alltogether

### ISSUE THREAD

**Issue by dereuromark** [dereuromark/cakephp-hashid#1]
Some people might want to completely change the primary key internally upon read, and re-change it prior to save.

We should look into that useful option IMO.

**Comment by bravo-kernel** [comment]
:+1:

**Comment by dereuromark** [comment]
@bravo-kernel What if someone uses primary key validation?
We need to exchange then prior to validation upon marshall?

**Comment by dereuromark** [comment]
Solved! See http://sandbox3.dereuromark.de/sandbox/hashids/pagination

Gotcha on top: Debug mode feature - to see the actual ids appended in debug mode.
