### ISSUE TITLE
Validator not working with Hashid behavior

### ISSUE THREAD

**Issue by fijnmedia** [dereuromark/cakephp-hashid#11]
When using the validationDefault method in a Table Class with a validateUnique rule, the validator doesn't work properly.

`
public function validationDefault(Validator $validator)
    {
        $validator->add('email', 'unique', [
            'rule' => 'validateUnique',
            'provider' => 'table',     
            'message' => 'Foo'       
        ]);
`

**Comment by dereuromark** [comment]
What is the generated SQL query?

**Comment by fijnmedia** [comment]
Thank you for your reply.

```
SELECT 
  1 AS `existing` 
FROM 
  users Users 
WHERE 
  Users.email = 'email@email.nl' 
LIMIT 
  1
```

1 row as result

**Comment by dereuromark** [comment]
Sounds like you might need a custom unique validator rule here.
Do you think we can hook into the existing one or the `Table::validateUnique()` from the behavior?

**Comment by fijnmedia** [comment]
I have too look deeper in the behavior when I have the time. I really appreciate all the work you've done the past years! Thanks!

**Comment by dereuromark** [comment]
Where you able to trace down the details?
