### ISSUE TITLE
Invalid integer, the id must be >= 1

### ISSUE THREAD

**Issue by danbuntu** [dereuromark/cakephp-hashid#17]
Hello

I've just installed this plugin using the drop in instructions.

Some of my pages  are working fine and the ids are hashing as expected.
On a lot of the pages though I get:

Invalid integer, the id must be >= 1

What am I doing wrong please?

**Comment by dereuromark** [comment]
A stracktrace and more details might be helpful.

**Comment by danbuntu** [comment]
So I stripped back every thing and stated to focus on one model.

I have an edit url that looks like:

`domain/clients/edit/2WP-335`
so the hashing at this point is working nicely.

When I hit save though with;
`
debug($client->errors());
`
I get:
`
[
	'id' => [
		'integer' => 'The provided value is invalid'
	]
]
`

the save block of my edit method looks like:

```
    $client = $this->Clients->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $client = $this->Clients->patchEntity($client, $this->request->getData());

            if ($this->Clients->save($client)) {
                $this->Flash->success(__('The client has been saved.'));

            }
            debug($client->errors());
            $this->Flash->error(__('The client could not be saved. Please, try again.'));
        }
```

**Comment by dereuromark** [comment]
Whats your validation rules?

**Comment by danbuntu** [comment]
The validation rules are the default cake baked ones I believe:

```
   public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');
```

**Comment by dereuromark** [comment]
maybe integer should not be used. use scalar () maybe to try.

**Comment by danbuntu** [comment]
I'm not sure what you mean by scalar - i couldn't find a reference to it in the cake docs.
integer is the default when baking models though.

**Comment by dereuromark** [comment]
Yeah but try it, that will help clear things up.

**Comment by dereuromark** [comment]
I think the validation rules do NOT fit to how this plugin works (as on patching the id field is a string when coming in), so you cannot use the defaults, use what I said and I am sure it will work.

I improved the docs: https://github.com/dereuromark/cakephp-hashid/tree/master/docs#validation
