### ISSUE TITLE
Plans to backport it for Cake 2.x

### ISSUE THREAD

**Issue by fr0z3nfyr** [dereuromark/cakephp-hashid#19]
Hi -

Thanks for your awesome work.

I have a project that is running on Cake 2.6.3 (MySQL 5.6, PHP 5 installed on Apache2 for Ubuntu 14.04 with SSL configured with Letsencrypt and scripts to automatically handle SSL certifiecates' expiry). The project is just too huge to attempt an upgrade to Cake 3 without breaking couple of things. So we decided to run it as is and planning to start working on re-building the app with Cake 3.6 with completely fresh DB schema (probably different datasource altogether). Anyway, that was the background.

Now, the query (sorry for using Github issues) - Can you think of any problems that we may face or must solve if we attempt to backport this plugin for Cake 2.x? Just want to be prepared before diving into it without knowing the obvious consequences.

Thanks in advance. 

Cheers!

**Comment by dereuromark** [comment]
I think technically, 2.x is too outdated to be able to do such changes.
If you find a solution we can open a 2.x branch here, please PR this then.
