### ISSUE TITLE
Apply Hashid also for foreignKey

### ISSUE THREAD

**Issue by wel0z** [dereuromark/cakephp-hashid#28]
Is there a way to hash also foreignk_key ?

**Comment by dereuromark** [comment]
The idea is that only what you put into the view/ID/ part needs to be "cloaked".
As such there is no need to do that for foreign keys, at least not with this default behavior.

**Comment by dereuromark** [comment]
Otherwise, you probably want to manually decode and use that to find the record you are looking for.
