### ISSUE TITLE
Impossible to attach ->matching() to finder

### ISSUE THREAD

**Issue by Modicrumb** [dereuromark/cakephp-hashid#31]
When using the finder the key is ambiguous because it's simply the primaryKey without the model alias in the where clause. This makes tagging on additional matching conditions impossible when using the finder. The trait also relies on configuration values which throw "Warning" notices if they aren't configured.

**Comment by dereuromark** [comment]
Are you able to make a PR with a fix?

**Comment by Modicrumb** [comment]
Sure.

**Comment by dereuromark** [comment]
Can you detail the exact error you get? Like SQL error or alike? 
I dont quite see the PR fixing it, as the row[$field] doesnt support dot alias syntax afaik.

**Comment by Modicrumb** [comment]
Error: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous

/vagrant/synergy/httpdocs/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php in line 38

SQL Query: SELECT CompaniesHospitals.id AS `CompaniesHospitals__id`, CompaniesHospitals.company_id AS `CompaniesHospitals__company_id`, CompaniesHospitals.hospital_id AS `CompaniesHospitals__hospital_id`, Companies.id AS `Companies__id` FROM companies_hospitals CompaniesHospitals INNER JOIN companies Companies ON (Companies.is_active = :c0 AND Companies.id = (CompaniesHospitals.company_id)) WHERE (id = :c1 AND id = :c2) LIMIT 1

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-hashid/pull/32/files#diff-7fa1a3f1d5e740ab3abffe55d5e19e40R260 is what you want to change.

**Comment by Modicrumb** [comment]
I've revised it to be so
