### ISSUE TITLE
configure array options min_hash_length and alphabet

### ISSUE THREAD

**Issue by allandiego** [dereuromark/cakephp-hashid#4]
Hello,

I think it would be interesting to create in the configuration array +2 parameters to access the options of the hashids constructor  `$min_hash_length` and `$alphabet` in addition to the `$salt` that already exists

Hashids:
`public function __construct($salt = '', $min_hash_length = 0, $alphabet = '')`

**Comment by dereuromark** [comment]
Feel free to make a PR.
Maybe minHashLength as naming, but sure.

**Comment by dereuromark** [comment]
PR now open.
