### ISSUE TITLE
does using data types ,instead of mapping increase the performance?

### ISSUE THREAD

**Issue by eymen-elkum** [dereuromark/cakephp-hashid#8]
Hi @dereuromark 
I am not expert in Cake, so I dont have an idea about this so I just wonder if using the [data types](http://book.cakephp.org/3.0/en/orm/database-basics.html#mapping-custom-datatypes-to-sql-expressions) ,instead of mapping the result make sense for the performance

**Comment by dereuromark** [comment]
Where would we do that inside this plugin? The plugin is only about handling primary keys and alike.

**Comment by eymen-elkum** [comment]
yes inside the plugin, the idea is to make a new data type named HashedId for example, then we set this type to our id to be tow way manipulated .
I thought that this may make performance more well, and code more clean

**Comment by dereuromark** [comment]
We could try it with a PR and compare some runtime statistics etc.
If you want to feel free to make a branch with these changes.

**Comment by eymen-elkum** [comment]
OK, I will try as soon as possible

**Comment by eymen-elkum** [comment]
sorry because I didn't worked with this
